services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-private internet access}
      - VPN_TYPE=${VPN_TYPE:-openvpn}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${VPN_SERVER_REGIONS:-SE Stockholm}
      - TZ=${TZ:-Europe/Stockholm}
    volumes:
      - /opt/docker/gluetun:/gluetun
    ports:
      - 8080:8080      # qBittorrent WebUI
      - 6881:6881      # BitTorrent
      - 6881:6881/udp
    networks:
      - gluetunvpn
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    user: "0:0"
    environment:
      - WEBUI_PORT=8080
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
      - TZ=${TZ:-Europe/Stockholm}
    volumes:
      - /opt/docker/qbittorrent/config2:/config
      - /mnt/media/movies:/movies
      - /mnt/media/tv:/tv
    restart: unless-stopped

networks:
  gluetunvpn:
    name: qbittorrent_gluetunvpn_default
